### ISSUE TITLE
Windows server 2004 has IIS application pool connection limit of 10

### ISSUE THREAD

**Issue by azkamil** [microsoft/containerregistry#37] opened 2020-11-11 15:26 UTC
Hi,

In our docker build we changed our base windows image from 1809 to **mcr.microsoft.com/windows:2004**
After this our application(on IIS) runs into timeout under a minimal load, no connection can be established.
Analyzing w3wp dump gave us a hint that the cause maybe the max connection count of 10 per IIS application pool. As seen in the screenshot the number stopped increasing at 10. In 1809 we had over 70 connections.
This is somehow very similar to the limit of 10 for Desktop Windows version.
This problem did not occurred while testing with **mcr.microsoft.com/windows/servercore:2004** . The connection count went over 20. We cannot use servercore version due missing functionality.

![10con](https://user-images.githubusercontent.com/2872951/98828283-2efc7e80-2438-11eb-9585-7dfc50b58cf7.PNG)

FYI As a host windows version we use Azure OS image sku: datacenter-core-2004-with-containers-smalldisk

Thanks

**Comment by azkamil** [comment] 2020-11-11 16:31
I noticed that this is a wrong repo for this issue. I opened a new case here
https://github.com/microsoft/Windows-Containers/issues/73

**Comment by bariscaglar** [comment] 2020-12-02 20:41
Closing since the correct home for the issue is found

**Closed by bariscaglar** 2020-12-02 20:41 UTC
