### ISSUE TITLE
.NET Core SDK 3.1 Debian 10 images are throwing image configuration errors I/O timeout

### ISSUE THREAD

**Issue by 4deeptech** [microsoft/containerregistry#10] opened 2019-12-06 22:26 UTC
I tried yesterday and again today to pull and use the Debian 10 '3.1.100' SDK image and get i/o timeout errors pulling image configuration. The 3.0.100 image reference does not do this.

Error:
error pulling image configuration: Get https://mcreus0.blob.core.windows.net/aba285c624a04409823b708c7a50e7b9-jttfjm99vo//docker/registry/v2/blobs/sha256/98/9817c25953a8ede59da1b397aa096c5ba269bbd969f55f1819393dda35f9d19f/data?se=2019-12-06T22%3A24%3A25Z&sig=n9whbNNyggFZrjyz9yyFU60hF3bgyf4yYno%2FVqpsZzM%3D&sp=r&sr=b&sv=2016-05-31&regid=aba285c624a04409823b708c7a50e7b9: dial tcp: lookup mcreus0.blob.core.windows.net on 192.168.65.1:53: read udp 192.168.65.3:43777->192.168.65.1:53: i/o timeout

Image reference being used is:

FROM mcr.microsoft.com/dotnet/core/sdk:3.1.100

This is using VSCode remote containers with Docker Desktop. I just now switched my docker file back to:

FROM mcr.microsoft.com/dotnet/core/sdk:3.0.100

and it fired right up.

Anyone else run into this or know what's going on?

**Comment by mbrown555** [comment] 2019-12-06 23:18
@4deeptech , are you still seeing this issue? I'm able to do a pull of the sdk:3.1.100 without a problem, so it doesn't seem to be any issue with MCR:

>docker pull mcr.microsoft.com/dotnet/core/sdk:3.1.100
3.1.100: Pulling from dotnet/core/sdk
d0c6a1b3dba2: Pull complete                                                                                             6d237e860928: Pull complete                                                                                             7e5ea318ffb6: Pull complete                                                                                             0d81a424c319: Pull complete                                                                                             b4616de64347: Pull complete                                                                                             2e124638c655: Pull complete                                                                                             6a56bf87cd91: Pull complete                                                                                             d787596c16a0: Pull complete                                                                                             Digest: sha256:1dbbb0b5f797db3f6a48499cd60d3a329d44bfce5871c7143393e977cc490bcc
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/sdk:3.1.100
mcr.microsoft.com/dotnet/core/sdk:3.1.100

**Comment by mbrown555** [comment] 2019-12-06 23:21
If it's still failing, can you try a ping of mcr.microsoft.com to see what region you're pulling from? For example:

>ping mcr.microsoft.com
Pinging rpm1118wus.**westus**.cloudapp.azure.com [40.112.242.158] with 32 bytes of data:
Request timed out.

Shows I'm pulling from westus region. I want to make sure the image isn't corrupt in a different region.

**Comment by 4deeptech** [comment] 2019-12-09 15:31
Tried this morning and it still failed. I capture the output to post here.
```Sending build context to Docker daemon   5.12kB
Step 1/12 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1.100
Get https://mcr.microsoft.com/v2/: dial tcp: lookup mcr.microsoft.com on 192.168.65.1:53: read udp 192.168.65.3:40933->192.168.65.1:53: i/o timeout
Failed: Building an image from the Dockerfile (this can take a while).
Command failed: C:\Program Files\Docker\Docker\Resources\bin\docker.exe build -f d:\GitHub\Stratify.Scout\.devcontainer\Dockerfile -t vsc-stratify.scout-0626897d0a096a8d8ba8eb31d6d0f650 d:\GitHub\Stratify.Scout\.devcontainer
```
For comparison, I immediate changed my docker file to use 3.0.100 and it worked right away. Here's the output from that as it got started.

```
Sending build context to Docker daemon   5.12kB
Step 1/12 : FROM mcr.microsoft.com/dotnet/core/sdk:3.0.100
 ---> 4422e7fb740c
Step 2/12 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 51b07042ae85
Step 3/12 : ARG USERNAME=vscode
 ---> Using cache
 ---> 9c235f70f5da
Step 4/12 : ARG USER_UID=1000
 ---> Using cache
 ---> 6b8fb5dc578a
Step 5/12 : ARG USER_GID=$USER_UID
 ---> Using cache
 ---> 38a9bc53eace
```

Also, pinging mcr.microsoft.com returned the following:
```
rpm1118eus.eastus.cloudapp.azure.com [40.71.10.214]
```
Thanks for looking into this.

**Comment by 4deeptech** [comment] 2019-12-09 19:09
After fiddling with my local hosts file to try to trick it to use the westus images and rebooting/restarting the docker desktop services, this now works. Note: I removed the hosts file changes and let DNS do its thing without me mucking with it.  So not sure what changed. Did you guys do something on your side or was this a local machine thing?  Doing a docker pull with 3.1.100 clearly didn't work before but now does.

**Comment by jhkimnew** [comment] 2019-12-10 00:39
Hi, I noticed there was a change recently for our traffic manager. Recently the ip address was updated from 40.71.10.215 to 40.71.10.214. But I am not sure if that is related to your issue or not yet. Would you please check if the issue happens on other machines? If it is still reproducible, please check what IP is shown with resolving mcr.microsoft.com in order to confirm if the issue is related to using a wrong IP address or not.

**Comment by rotata** [comment] 2020-01-22 23:21
@4deeptech  Is this issue still ocurring?

**Comment by bariscaglar** [comment] 2020-03-25 18:28
This has been inactive for a while, let us know if the issue still persists.

**Closed by bariscaglar** 2020-03-25 18:28 UTC
