### ISSUE TITLE
Cant pull Microsoft runtime images : 503 Service Unavailable

### ISSUE THREAD

**Issue by ksrivastav** [microsoft/containerregistry#157] opened 2024-01-21 03:30 UTC
I am trying to pull Microsoft runtime images and receiving   503 Service Unavailable. 
**Commands on which error is received** 
1. docker pull mcr.microsoft.com/dotnet/aspnet:8.0
2. docker pull mcr.microsoft.com/dotnet/sdk:8.0

**Error Received** 
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable

**Comment by oriser** [comment] 2024-01-21 03:34
Same here for `mcr.microsoft.com/playwright/python:v1.40.0-jammy`

**Comment by ggiesen** [comment] 2024-01-21 03:44
Same here for `mcr.microsoft.com/powershell:latest`

**Comment by kyleli666** [comment] 2024-01-21 04:30
Same here for dotnet, we temporarily change "mcr.microsoft.com/dotnet" to "registry.cn-hangzhou.aliyuncs.com/newbe36524"...
It was working early this morning around 10AM(UTC+8), then it replies with 401 Unauthorized, and finally 503 Unavailable.

**Comment by moo-the-cow** [comment] 2024-01-21 04:33
confirmed from EU

**Comment by emrys90** [comment] 2024-01-21 04:51
Same here for `mcr.microsoft.com/dotnet/sdk:8.0`

**Comment by oriser** [comment] 2024-01-21 05:33
Looks like it resolved

**Comment by AndreHamilton-MSFT** [comment] 2024-04-23 14:01
@Ganesh1991 can you share what region you are in. Is this still ongoing? We are currently investigating some issues impacting azure jio india west and working on mitigation

**Comment by AndreHamilton-MSFT** [comment] 2024-04-23 17:50
@ksrivastav and for other users. The outage on this date is linked to this specific azure incident https://azure.status.microsoft/status/history/?trackingId=NKRF-1TG

**Comment by theofred** [comment] 2024-04-24 20:14
Had problems creating a devcontainer based on `mcr.microsoft.com/devcontainers/dotnet:1-6.0` from Germany right now.

Used VPN to connect to New York and it worked just fine.

**Comment by AndreHamilton-MSFT** [comment] 2024-04-30 17:07
@ksrivastav closing since ive linked the appropriate outage.

**Closed by AndreHamilton-MSFT** 2024-04-30 17:07 UTC
